import Head from 'next/head'
import Image from 'next/image'
import { Container, Table, Header } from '../components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title={'Orders'} />

      <main>
        <Container>
          <Table />
        </Container>
      </main>
    </>
  )
}
